language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1
  - 7.2

install:
  - composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - vendor/bin/phpcs

after_success:
  - bash <(curl -s https://codecov.io/bash)
