language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

before_install:
  - phpenv config-add travis-php.ini

install:
  - composer install --no-interaction --prefer-dist

script:
  - make build-travis

after_success:
  - bash <(curl -s https://codecov.io/bash)

# Added comment - 
